set(COMPOSER_REFERENCE_CMAKE_VERSION "4.3.3" CACHE INTERNAL "Reference CMake pin")
set(COMPOSER_MINIMUM_CMAKE_VERSION "3.22.0" CACHE INTERNAL "Compatible CMake floor")
set(COMPOSER_REFERENCE_NINJA_VERSION "1.13.2" CACHE INTERNAL "Reference Ninja pin")

message(STATUS
    "Composer reference tools: CMake ${COMPOSER_REFERENCE_CMAKE_VERSION}, "
    "Ninja ${COMPOSER_REFERENCE_NINJA_VERSION}")
